version: '3.7'
services: 
  mongo-express:
    image: mongo-express
    ports:
      - 8088:8880
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb 
    restart : unless-stopped
